routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courier', 'Admin\CouriersController');
Route::resource('customer/type', 'Admin\CustomerTypeController');
Route::resource('customer', 'Admin\CustomerController');
Route::resource('package', 'Admin\PackageController');
Route::resource('shipment/status', 'Admin\ShipmentStatusController');
Route::resource('shipment/service', 'Admin\ShipmentServiceController');
Route::resource('shipment/checkpoint', 'Admin\ShipmentChekpointController');
Route::resource('shipment', 'Admin\ShipmentController');

app/Models/Shipment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Shipment extends Model
{
    //
    protected $fillable = [
        'shipment_shipper',
        'shipment_consignee',
        'shipment_courier',
        'shipment_origin',
        'shipment_destination',
        'shipment_date',
        'shipment_expected_delivery',
        'shipment_service',
        'shipment_package_count',
    ];

    public function shippers()
    {
        return $this->belongsTo('App\Models\Customer', 'shipment_shipper')->where('customer_type', 1);
    }

    public function consignees()
    {
        return $this->belongsTo('App\Models\Customer', 'shipment_consignee')->where('customer_type', 2);
    }

    public function couriers()
    {
        return $this->hasOne('App\Models\Courier', 'id');
    }

    public function services()
    {
        return $this->hasOne('App\Models\ShipmentService', 'id');
    }

    public function shipmentLists()
    {
      return $this->belongsTo('App\Models\ShipmentPackageList', 'package_id');
    }
}

app/Http/Controllers/Admin/ShipmentController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use App\Models\Shipment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;

class ShipmentController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      $shipments = Shipment::with(['shippers', 'consignees', 'couriers', 'services'])->get();

      return view('admin.shipments.list', ['shipments' => $shipments]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      return view('admin.shipments.form');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $shipments = Shipment::create($request->all());
      return redirect()->route('shipment.index')->with('alert-success','Berhasil Menambahkan Data!');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      $shipments = Shipment::find($id);
      return view('admin.shipments.detail', ['shipments' => $shipments]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      $shipments = Shipment::find($id);
      return view('admin.shipments.form', ['shipments' => $shipments]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
      $shipments = Shipment::find($id);
      $shipments->shipment_shipper = $request->shipment_shipper;
      $shipments->shipment_consignee = $request->shipment_consignee;
      $shipments->shipment_courier = $request->shipment_courier;
      $shipments->shipment_origin = $request->shipment_origin;
      $shipments->shipment_destination = $request->shipment_destination;
      $shipments->shipment_date = $request->shipment_date;
      $shipments->shipment_expected_delivery = $request->shipment_expected_delivery;
      $shipments->shipment_service = $request->shipment_service;
      $shipments->shipment_package_count = $request->shipment_package_count;
      $shipments->save();

      return redirect()->route('shipment.index')->with('alert-success','Berhasil Memperbarui Data!');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      $shipments = Shipment::destroy($id);
      return redirect()->route('shipment.index')->with('alert-success','Berhasil Menghapus Data!');
  }
}

resources/views/admin/shipments/services/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Data Couriers
                	<a style="float: right;" class="btn btn-primary" href="{{ route('courier.index') }}">Back</a>
            	</div>

                <div class="panel-body">

                	
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/shipments/services/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Add Data Shipment Service
                	<a style="float: right;" class="btn btn-primary" href="{{ route('service.index') }}">Back</a>
            	</div>

                <div class="panel-body">

                    @if(@$services->exists) <?php  $url = route('service.update', @$services->id); ?>
                    @else <?php  $url = route('service.store'); ?>
                    @endif
                	<form class="form-horizontal" action="{{ $url }}" method="POST">

                        @if (@$services->exists)
                            {{ method_field('PUT') }}
                        @else
                            {{ method_field('POST') }}
                        @endif

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('service_name') ? ' has-error' : '' }}">
                            <label for="service_name" class="col-md-4 control-label">Service Name</label>

                            <div class="col-md-6">
                                <input id="service_name" type="text" class="form-control" name="service_name" value="{{ @$services->service_name }}"required>

                                @if ($errors->has('service_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('service_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('service_type') ? ' has-error' : '' }}">
                            <label for="service_type" class="col-md-4 control-label">Service Type</label>

                            <div class="col-md-6">
                                <input id="service_type" type="text" class="form-control" name="service_type" value="{{ @$services->service_type }}"required>

                                @if ($errors->has('service_type'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('service_type') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button service="submit" class="btn btn-primary">
                                    @if (@$services->exists)
                                        Update Service
                                    @else
                                        Add Service
                                    @endif
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/shipments/services/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Data Shipment Service
                	<a style="float: right;" class="btn btn-primary" href="{{ route('service.create') }}">Add</a>
            	</div>

                <div class="panel-body">

                	@if(Session::has('alert-success'))
		                <div class="alert alert-success">
		                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
		                </div>
  		            @endif

                	<table class="table table-stripped table-responsive">
                		<thead>
                			<th>#</th>
                			<th>Service name</th>
                			<th>Service type</th>
                			<th></th>
                		</thead>
                		<tbody>
                			@php $no = 1; @endphp
                			@foreach ($services as $service)
        								<tr>
        									<td>{{ $no++ }}</td>
        									<td>{{ $service->service_name }}</td>
        									<td>{{ $service->service_type }}</td>
        									<td>
        										<form action="{{ route('service.destroy', $service->id) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE') }}
                              <a class="btn btn-sm btn-info" href="{{ route('service.edit', $service->id) }}">Edit</a>
                              <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                      			</form>
                    			</td>
        								</tr>
        							@endforeach
                		</tbody>
                	</table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection