routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('courier', 'Admin\CouriersController');
Route::resource('customer/type', 'Admin\CustomerTypeController');
Route::resource('customer', 'Admin\CustomerController');
Route::resource('package', 'Admin\PackageController');
Route::resource('shipment/status', 'Admin\ShipmentStatusController');
Route::resource('shipment/service', 'Admin\ShipmentServiceController');
Route::resource('shipment/checkpoint', 'Admin\ShipmentChekpointController');
Route::resource('shipment', 'Admin\ShipmentController');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //
    protected $fillable = [
        'customer_name',
        'customer_address',
        'customer_phone',
        'customer_type',
    ];

    public function types()
    {
        return $this->belongsTo('App\Models\CustomerType', 'customer_type');
    }

    public function shipmentShippers()
    {
        return $this->hasMany('App\Models\Shipment', 'shipment_shipper');
    }

    public function shipmentConsignees()
    {
        return $this->hasMany('App\Models\Shipment', 'shipment_consignee');
    }

}

app/Models/CustomerType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerType extends Model
{
    //
    protected $fillable = [
        'customer_type_name',
    ];

    public function customers()
    {
        return $this->hasMany('App\Models\Customer', 'customer_type');
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Customer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;

class CustomerController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      $customers = Customer::with('types')->get();
      return view('admin.customers.list', ['customers' => $customers]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      return view('admin.customers.form');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
      $customers = Customer::create($request->all());
      return redirect()->route('customer.index')->with('alert-success','Berhasil Menambahkan Data!');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      $customers = Customer::find($id);
      return view('admin.customers.detail', ['customers' => $customers]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
      $customers = Customer::find($id);
      return view('admin.customers.form', ['customers' => $customers]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
      $customers = Customer::find($id);
      $customers->customer_name = $request->customer_name;
      $customers->customer_address = $request->customer_address;
      $customers->customer_phone = $request->customer_phone;
      $customers->customer_type = $request->customer_type;
      $customers->save();

      return redirect()->route('customer.index')->with('alert-success','Berhasil Memperbarui Data!');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      $customers = Customer::destroy($id);
      return redirect()->route('customer.index')->with('alert-success','Berhasil Menghapus Data!');
  }
}

resources/views/admin/customers/types/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Data Couriers
                	<a style="float: right;" class="btn btn-primary" href="{{ route('courier.index') }}">Back</a>
            	</div>

                <div class="panel-body">

                	
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/customers/types/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Add Data Customer Types
                	<a style="float: right;" class="btn btn-primary" href="{{ route('type.index') }}">Back</a>
            	</div>

                <div class="panel-body">

                    @if(@$types->exists) <?php  $url = route('type.update', @$types->id); ?>
                    @else <?php  $url = route('type.store'); ?>
                    @endif
                	<form class="form-horizontal" action="{{ $url }}" method="POST">

                        @if (@$types->exists)
                            {{ method_field('PUT') }}
                        @else
                            {{ method_field('POST') }}
                        @endif

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('customer_type_name') ? ' has-error' : '' }}">
                            <label for="customer_type_name" class="col-md-4 control-label">Customer Type Name</label>

                            <div class="col-md-6">
                                <input id="customer_type_name" type="text" class="form-control" name="customer_type_name" value="{{ @$customers->customer_type_name }}"required>

                                @if ($errors->has('customer_type_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('customer_type_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    @if (@$types->exists)
                                        Update Types
                                    @else
                                        Add Types
                                    @endif
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/customers/types/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                	Data Customer Type
                	<a style="float: right;" class="btn btn-primary" href="{{ route('type.create') }}">Add</a>
            	</div>

                <div class="panel-body">

                	@if(Session::has('alert-success'))
		                <div class="alert alert-success">
		                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
		                </div>
		            @endif

                	<table class="table table-stripped table-responsive">
                		<thead>
                			<th>#</th>
                			<th>Customer type name</th>
                			<th></th>
                		</thead>
                		<tbody>
                			@php $no = 1; @endphp
                			@foreach ($types as $type)
        								<tr>
        									<td>{{ $no++ }}</td>
        									<td>{{ $type->customer_type_name }}</td>
        									<td>
        										<form action="{{ route('type.destroy', $type->id) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('DELETE') }}
                              <a class="btn btn-sm btn-info" href="{{ route('type.edit', $type->id) }}">Edit</a>
                              <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                      			</form>
                    			</td>
        								</tr>
        							@endforeach
                		</tbody>
                	</table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection